on:
  push:
    branches: [main]

jobs:
  build:
    if: ${{ github.event.repository.url != 'https://github.com/Yoowatney/GomGomFront' }}
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v3
      - name : Create directory
        run : sh ./build.sh || ls -al
          echo ${{ github.event.repository.name }}
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          destination-github-username: "Yoowatney"
          destination-repository-name: "GomGomFront"
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
